#Plots of Morris indices (22 inputs) generated by ML emulators
#============================================================================
# Random Forest and ANN emulators for 6 output targets by 22 Inputs
#   Latitude varied [3 Sowing = 1,2,3; 1 sampling level = 1000 samples]


rm(list = ls())

library(ggplot2)
library(grid)
library(gridExtra)
library(dplyr)
library(viridis)

options(scipen=999)
#format(summary(caps), big.mark = ",") # using big.mark to add commas

# define the datapaths / files / settings
# project load directory = working directory ["U:/Paper #3/Data and Code/R"]
dataPath <- "./Reports/"

# sample name "ANN_22MegaMorrisTest_E1.csv"
ANN_megainputs <- "ANN_22MegaMorrisTest_"
RF_megainputs <- "RF_22MegaMorrisTest_"
#versions <- c("E1","E2","E3","G1","G2","G3","H1","H2","H3")
versions <- c("G2")
inputFileExt <- ".csv"


# Output strings
outputPath <- "./Reports/Figures/"

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#Start loop of input file sets
for (loopCnt in (1:length(versions)))  {
  #Load  .csv data file of Morris data
  
  #ANN models
  sourceFile <- paste0(dataPath,ANN_megainputs,versions[loopCnt],inputFileExt)
  ann_mega_df <- read.csv(sourceFile)
  
  #RF models
  sourceFile <- paste0(dataPath,RF_megainputs,versions[loopCnt],inputFileExt)
  rf_mega_df <- read.csv(sourceFile)
  
  
  # Combine the two ML models' dataframes into a single data source
  allScenarios_df <- rbind(ann_mega_df,
                           rf_mega_df
                           )

  
  # convert target names to report format
  allScenarios_df$target[allScenarios_df$target == "EmergenceDAS"] <- "(i) EmergenceDAS"
  allScenarios_df$target[allScenarios_df$target == "FloweringDAS"] <- "(ii) FloweringDAS"
  allScenarios_df$target[allScenarios_df$target == "PoddingDAS"]   <- "(iii) PoddingDAS"
  allScenarios_df$target[allScenarios_df$target == "MaturityDAS"]  <- "(iv) MaturityDAS"
  allScenarios_df$target[allScenarios_df$target == "Biomass"]      <- "(v) Biomass"
  allScenarios_df$target[allScenarios_df$target == "GrainWt"]      <- "(vi) GrainWt"
  
   Emergence_df <- subset(allScenarios_df, target == "(i) EmergenceDAS")
   Flowering_df <- subset(allScenarios_df, target == "(ii) FloweringDAS")
   Podding_df <- subset(allScenarios_df, target == "(iii) PoddingDAS")
   Maturity_df <- subset(allScenarios_df, target == "(iv) MaturityDAS")
   Biomass_df <- subset(allScenarios_df, target == "(v) Biomass")
   GrainWt_df <- subset(allScenarios_df, target == "(vi) GrainWt")
   
  #>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  #Generate graphs
  #===============
  

  #^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  # generate 1 plot for each Target. Use Grid Arrange to create output plot
  #
  titleTxt <- paste0("Morris analysis using 22 machine learning inputs - Summary ")
  
      # ggplot2 plot EmergenceDAS 
      morris_Plot_EmergenceDAS <- ggplot(Emergence_df, aes(x=mu.star, y=sigma, color = model, label=input )) +
              labs(title = "EmergenceDAS") +
              xlab("mu* (days)")+
              ylab("\u03C3 (days)")+
              geom_point()+
              geom_text(hjust=0,vjust=1,  size = 2.5, check_overlap = TRUE, nudge_y = 0.2)+
              scale_color_manual(name = "model",values=c("#D55E00","darkgreen"))+
              scale_x_continuous(limits = c(0, 12)) +
              theme_bw() +
              theme(legend.position = "none")
      
      
      # ggplot2 plot FloweringDAS 
      morris_Plot_FloweringDAS <- ggplot(Flowering_df, aes(x=mu.star, y=sigma, color = model, label=input )) +
        labs(title = "FloweringDAS") +
        xlab("mu* (days)")+
        ylab("\u03C3 (days)")+
        geom_point()+
        geom_text(hjust=0,vjust=1,  size = 2.5, check_overlap = TRUE, nudge_x = 0.2)+
        scale_color_manual(name = "model",values=c("#D55E00","darkgreen"))+
        scale_x_continuous(limits = c(0, 30)) +
        theme_bw() +
        theme(legend.position = "none")
      
      
      
      # ggplot2 plot PoddingDAS 
      morris_Plot_PoddingDAS <- ggplot(Podding_df, aes(x=mu.star, y=sigma, color = model, label=input )) +
        labs(title = "PoddingDAS") +
        xlab("mu* (days)")+
        ylab("\u03C3 (days)")+
        geom_point()+
        geom_text(hjust=0,vjust=1,  size = 2.5, check_overlap = TRUE, nudge_x = 0.2)+
        scale_color_manual(name = "model",values=c("#D55E00","darkgreen"))+
        scale_x_continuous(limits = c(0, 80)) +
        theme_bw() +
        theme(legend.position = "none")
      
      
      # ggplot2 plot MaturityDAS 
      morris_Plot_MaturityDAS <- ggplot(Maturity_df, aes(x=mu.star, y=sigma, color = model, label=input )) +
        labs(title = "MaturityDAS") +
        xlab("mu* (days)")+
        ylab("\u03C3 (days)")+
        geom_point()+
        geom_text(hjust=0,vjust=1,  size = 2.5, check_overlap = TRUE, nudge_x = 0.2)+
        scale_color_manual(name = "model",values=c("#D55E00","darkgreen"))+
        scale_x_continuous(limits = c(0, 80)) +
        theme_bw() +
        theme(legend.position = "none")
      
      
      # ggplot2 plot Biomass 
      morris_Plot_Biomass <- ggplot(Biomass_df, aes(x=mu.star, y=sigma, color = model, label=input )) +
        labs(title = "Biomass") +
        xlab("mu* (kg/ha)")+
        ylab("\u03C3 (kg/ha)")+
        geom_point()+
        geom_text(hjust=0,vjust=1,  size = 2.5, check_overlap = TRUE, nudge_x = 0.2)+
        scale_color_manual(name = "model",values=c("#D55E00","darkgreen"))+
        scale_x_continuous(limits = c(0, 450)) +
        theme_bw() +
        theme(legend.position = "bottom")
      
      # ggplot2 plot GrainWt 
      morris_Plot_GrainWt <- ggplot(GrainWt_df, aes(x=mu.star, y=sigma, color = model, label=input )) +
        labs(title = "GrainWt") +
        xlab("mu* (kg/ha)")+
        ylab("\u03C3 (kg/ha)")+
        geom_point()+
        geom_text(hjust=0,vjust=1,  size = 2.5, check_overlap = TRUE, nudge_x = 0.2)+
        scale_color_manual(name = "model",values=c("#D55E00","darkgreen"))+
        scale_x_continuous(limits = c(0, 350)) +
        theme_bw() +
        theme(legend.position = "bottom")
      

      outputPlot <- paste0("./Reports/Figures/MegaMorris22_Summary_no-OL.png")
      
       png(outputPlot, width=18, height=25, units='cm', res=300)
       print(
      
            grid.arrange(morris_Plot_EmergenceDAS,morris_Plot_FloweringDAS,
                   morris_Plot_PoddingDAS, morris_Plot_MaturityDAS,
                   morris_Plot_Biomass, morris_Plot_GrainWt,
                   ncol = 2, heights=unit(c(7,7,9),c("cm")))
                   #top="Morris Analysis - 22 inputs for Machine Learning emulators")
      
   )
   
   dev.off()
  

}


