#Plots of Sobol indices (22 inputs) generated by ML emulators
#============================================================================
# Random Forest and ANN emulators for 6 output targets by 22 Inputs
#   Latitude varied [3 Sowing = 1,2,3; 1 sampling level = 100000 samples]


rm(list = ls())

library(ggplot2)
library(dplyr)

options(scipen=999)
#format(summary(caps), big.mark = ",") # using big.mark to add commas

# define the datapaths / files / settings
# project load directory = working directory ["U:/Paper #3/Data and Code/R"]
dataPath <- "./Reports/"

# sample name "ANN_MegaSobolTest_E1.csv"
ANN_megainputs <- "ANN_MegaSobolTest_FixedLat3_"
RF_megainputs <- "RF_MegaSobolTest_FixedLat_"
#versions <- c("E1","E2","E3","G1","G2","G3","H1","H2","H3")
versions <- c("E2","G2","H2")
inputFileExt <- ".csv"


# Output strings
outputPath <- "./Reports/Figures/"
# Emerald_graph1Name <- "Plot_MegaSobol_Emerald"
# Gunnedah_graph1Name <- "Plot_MegaSobol_Gunnedah"
# Horsham_graph1Name <- "Plot_MegaSobol_Horsham"

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#Start loop of input file sets
for (loopCnt in (1:length(versions)))  {
  #Load  .csv data file of SOBOL data
  
  #ANN models
  sourceFile <- paste0(dataPath,ANN_megainputs,versions[loopCnt],inputFileExt)
  ann_mega_df <- read.csv(sourceFile)
  
  #RF models
  sourceFile <- paste0(dataPath,RF_megainputs,versions[loopCnt],inputFileExt)
  rf_mega_df <- read.csv(sourceFile)
  
  
  # Combine the two ML models' dataframes into a single data source
  allScenarios_df <- rbind(ann_mega_df,
                           rf_mega_df
                           )
  
  # convert index names to report format
  allScenarios_df$index[allScenarios_df$model == "RF" & allScenarios_df$index == "FirstOrder"]      <- "FirstOrder_RF"
  allScenarios_df$index[allScenarios_df$model == "RF" & allScenarios_df$index == "TotalEffects"]   <- "TotalEffects_RF"
  allScenarios_df$index[allScenarios_df$model == "ANN" & allScenarios_df$index == "FirstOrder"]      <- "FirstOrder_ANN"
  allScenarios_df$index[allScenarios_df$model == "ANN" & allScenarios_df$index == "TotalEffects"]   <- "TotalEffects_ANN"
  
  
  # convert target names to report format
  allScenarios_df$target[allScenarios_df$target == "EmergenceDAS"] <- "(i) EmergenceDAS"
  allScenarios_df$target[allScenarios_df$target == "FloweringDAS"] <- "(ii) FloweringDAS"
  allScenarios_df$target[allScenarios_df$target == "PoddingDAS"]   <- "(iii) PoddingDAS"
  allScenarios_df$target[allScenarios_df$target == "MaturityDAS"]  <- "(iv) MaturityDAS"
  allScenarios_df$target[allScenarios_df$target == "Biomass"]      <- "(v) Biomass"
  allScenarios_df$target[allScenarios_df$target == "GrainWt"]      <- "(vi) GrainWt"
  
  # Loc1Scenarios_df <- subset(allScenarios_df, location == "Emerald")
  # Loc2Scenarios_df <- subset(allScenarios_df, location == "Gunnedah")
  # Loc3Scenarios_df <- subset(allScenarios_df, location == "Horsham")
  
  #>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  #Generate graphs
  #===============
  
      # #Emerald
      # outputFile <- paste0(outputPath,Emerald_graph1Name,".png")
      # png(outputFile, width=18, height=25, units='cm', res=300)
      # print(
      #     # ggplot2 plot with confidence intervals    
      #     ci_Plot_Emerald <- ggplot(Loc1Scenarios_df, aes(x=input, y=original, color = index )) + 
      #             geom_point(aes(shape = index)) +
      #             #geom_errorbar(aes(ymin = min..c.i., ymax = max..c.i.)) +
      #             scale_color_discrete(name = "Index")+
      #             theme_bw() +
      #             theme(axis.text.x = element_text(angle = 90)) +
      #         facet_grid(target ~ .),
      # )
      # 
      # dev.off()
      # 
      # #Gunnedah
      # outputFile <- paste0(outputPath,Gunnedah_graph1Name,".png")
      # png(outputFile, width=18, height=25, units='cm', res=300)
      # print(
      #     # ggplot2 plot with confidence intervals    
      #     ci_Plot_Gunnedah <- ggplot(Loc2Scenarios_df, aes(x=input, y=original, color = index )) + 
      #         geom_point(aes(shape = index)) +
      #         #geom_errorbar(aes(ymin = min..c.i., ymax = max..c.i.)) +
      #         scale_color_discrete(name = "Index")+
      #         theme_bw() +
      #         theme(axis.text.x = element_text(angle = 90)) +
      #         facet_grid(target ~ .),
      # )
      # 
      # dev.off()
      # 
      # #Horsham
      # outputFile <- paste0(outputPath,Horsham_graph1Name,".png")
      # png(outputFile, width=18, height=25, units='cm', res=300)
      # print(
      #     # ggplot2 plot with confidence intervals    
      #     ci_Plot_Horsham <- ggplot(Loc3Scenarios_df, aes(x=input, y=original, color = index )) +
      #         geom_point(aes(shape = index)) +
      #         #geom_errorbar(aes(ymin = min..c.i., ymax = max..c.i.)) +
      #         scale_color_discrete(name = "Index")+
      #         theme_bw() +
      #         theme(axis.text.x = element_text(angle = 90)) +
      #         facet_grid(target ~ . )
      # )
      # 
      # dev.off()
  
  #^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  #3 locations combined
  titleTxt <- paste0("Sobol Analysis of 22 machine learning inputs for ",versions[loopCnt]," fixed Lat")
  outputPlot <- paste0("./Reports/Figures/MegaSobol_22Inputs_FixedLat3_" ,versions[loopCnt],".png")
  
  png(outputPlot, width=26, height=18, units='cm', res=300)
  print(
      # ggplot2 plot with facet grid  
      sobol_Plot_mega <- ggplot(allScenarios_df, aes(x=input, y=original, color = index )) +
              geom_point(aes(shape = index)) +
             # scale_color_discrete(name = "Index")+
              scale_shape_manual(name = "Index",values=c(16, 17, 5, 6))+
              scale_color_manual(name = "Index",values=c('#CC9966','lightgreen', '#993300', 'darkgreen'))+
              scale_size_manual(name = "Index",values=c(2,5,2,5))+
              labs(title = titleTxt) +
              xlab("Input")+
              ylab("Sobol index value")+
              theme_bw() +
              theme(plot.title=element_text(hjust=0.5))+
              theme(axis.text.x = element_text(angle = 90))+
              theme(strip.text.y = element_text(size = 6))+
              theme(legend.position = "bottom")  
        + facet_grid(target ~ . )
  )
  
  dev.off()
  

}


