#Error Bar plus XY plots of Confidence Ranges of Sobol indices (six inputs) generated by ML emulators
# Error Bar for selected CI plots. 
# XY plot for mean of CI ranges for convergence plots.
#====================================================================================================
# One location only: Gunnedah. One sowing only: Sowing 2 (DOY = 150)
# Random Forest and ANN emulators for 6 output targets by 6 Sampling levels (log scales used) c(10,100,1000,10000,50000,100000)
#

rm(list = ls())

library(ggplot2)
library(dplyr)


# define the datapaths / files / settings
# project load directory = working directory ["U:/Paper #3/Data and Code/R"]
dataPath <- "./Reports/"

RFconverge_EmergeDASFile <- "rf_Convergence_EmergenceDAS.csv"
RFconverge_FlowerDASFile <- "rf_Convergence_FloweringDAS.csv"
RFconverge_PoddingDASFile <- "rf_Convergence_PoddingDAS.csv"
RFconverge_MaturityDASFile <- "rf_Convergence_MaturityDAS.csv"
RFconverge_BiomassFile <- "rf_Convergence_Biomass.csv"
RFconverge_GrainWtFile <- "rf_Convergence_GrainWt.csv"

ANNconverge_EmergeDASFile <- "ann_Convergence_EmergenceDAS.csv"
ANNconverge_FlowerDASFile <- "ann_Convergence_FloweringDAS.csv"
ANNconverge_PoddingDASFile <- "ann_Convergence_PoddingDAS.csv"
ANNconverge_MaturityDASFile <- "ann_Convergence_MaturityDAS.csv"
ANNconverge_BiomassFile <- "ann_Convergence_Biomass.csv"
ANNconverge_GrainWtFile <- "ann_Convergence_GrainWt.csv"



# Output strings
outputPath <- "./Plots/"

options(scipen=999)
#format(summary(caps), big.mark = ",") # using big.mark to add commas

#********************************************************
#Load  .csv data file of SOBOL Convergence data

#RF models
#EmergenceDAS
sourceFile <- paste0(dataPath,RFconverge_EmergeDASFile)
rf_converge1_df <- read.csv(sourceFile)
#FloweringDAS
sourceFile <- paste0(dataPath,RFconverge_FlowerDASFile)
rf_converge2_df <- read.csv(sourceFile)
#PoddingDAS
sourceFile <- paste0(dataPath,RFconverge_PoddingDASFile)
rf_converge3_df <- read.csv(sourceFile)
#MaturityDAS
sourceFile <- paste0(dataPath,RFconverge_MaturityDASFile)
rf_converge4_df <- read.csv(sourceFile)
#Biomass
sourceFile <- paste0(dataPath,RFconverge_BiomassFile)
rf_converge5_df <- read.csv(sourceFile)
#GrainWt
sourceFile <- paste0(dataPath,RFconverge_GrainWtFile)
rf_converge6_df <- read.csv(sourceFile)

## ANN models
#EmergenceDAS
sourceFile <- paste0(dataPath,ANNconverge_EmergeDASFile)
ann_converge1_df <- read.csv(sourceFile)
#FloweringDAS
sourceFile <- paste0(dataPath,ANNconverge_FlowerDASFile)
ann_converge2_df <- read.csv(sourceFile)
#PoddingDAS
sourceFile <- paste0(dataPath,ANNconverge_PoddingDASFile)
ann_converge3_df <- read.csv(sourceFile)
#MaturityDAS
sourceFile <- paste0(dataPath,ANNconverge_MaturityDASFile)
ann_converge4_df <- read.csv(sourceFile)
#Biomass
sourceFile <- paste0(dataPath,ANNconverge_BiomassFile)
ann_converge5_df <- read.csv(sourceFile)
#GrainWt
sourceFile <- paste0(dataPath,ANNconverge_GrainWtFile)
ann_converge6_df <- read.csv(sourceFile)

# Combine 6 target dataframes into a single data source
converge_all_df <- rbind(rf_converge1_df,
                         rf_converge2_df,
                         rf_converge3_df,
                         rf_converge4_df,
                         rf_converge5_df,
                         rf_converge6_df,
                         ann_converge1_df,
                         ann_converge2_df,
                         ann_converge3_df,
                         ann_converge4_df,
                         ann_converge5_df,
                         ann_converge6_df
                        )

# Create mean ciRange values for each group of sampleSizes
convergeAllMeans_df <- converge_all_df %>% group_by(target,model,index,sampleSize) %>% mutate(meanByGroup = mean(ciRange))

# convert target names to report format
convergeAllMeans_df$target[convergeAllMeans_df$target == "EmergenceDAS"] <- "(a) EmergenceDAS"
convergeAllMeans_df$target[convergeAllMeans_df$target == "FloweringDAS"] <- "(b) FloweringDAS"
convergeAllMeans_df$target[convergeAllMeans_df$target == "PoddingDAS"]   <- "(c) PoddingDAS"
convergeAllMeans_df$target[convergeAllMeans_df$target == "MaturityDAS"]  <- "(d) MaturityDAS"
convergeAllMeans_df$target[convergeAllMeans_df$target == "Biomass"]      <- "(e) Biomass"
convergeAllMeans_df$target[convergeAllMeans_df$target == "GrainWt"]      <- "(f) GrainWt"

# convert index names to report format
convergeAllMeans_df$index[convergeAllMeans_df$model == "RF" & convergeAllMeans_df$index == "FirstOrder"]      <- "FirstOrder_RF"
convergeAllMeans_df$index[convergeAllMeans_df$model == "RF" & convergeAllMeans_df$index == "TotalEffects"]   <- "TotalEffects_RF"
convergeAllMeans_df$index[convergeAllMeans_df$model == "ANN" & convergeAllMeans_df$index == "FirstOrder"]      <- "FirstOrder_ANN"
convergeAllMeans_df$index[convergeAllMeans_df$model == "ANN" & convergeAllMeans_df$index == "TotalEffects"]   <- "TotalEffects_ANN"

# create a separate dataframe of selected details for extra plot
# [for Gunnedah Sowing 2 (only data) select for 100, 1000, and 10000 samples sizes for FloweringDAS, MaturityDAS and GrainWt]
#

convergeSelected_df <- subset(convergeAllMeans_df, sampleSize %in% c(100,1000,10000) 
                                                  & target %in% c("(b) FloweringDAS","(d) MaturityDAS","(f) GrainWt"))



#**************************************************************
#*Plotting panels 
#*
png('./Reports/Figures/Convergence_NoTitle.png', width=18, height=20, units='cm', res=300)
print(
    
    convergencePlot <- ggplot(convergeAllMeans_df, aes(x=sampleSize, y=meanByGroup, color = index )) +
                          geom_point()+
                          # scale_color_discrete(name = "Index")+
                          scale_shape_manual(name = "Index",values=c(16, 17, 5, 6))+
                          scale_color_manual(name = "Index",values=c('#CC9966','lightgreen', '#993300', 'darkgreen'))+
                          scale_size_manual(name = "Index",values=c(2,5,2,5))+
                          geom_line() +
                          scale_x_continuous(trans='log10')+
                          labs(#title = "Convergence of Sobol index mean band widths ",
                               #subtitle = "Confidence ranges averaged for six input parameters for each index",
                               x = "Sample Size - log scale", 
                               y = "Mean of ranges of index confidence intervals")+
                          theme_bw() +
                          theme(axis.text.x = element_text(angle = 90)) +
                          
                   facet_wrap(vars(target),ncol = 2)

)

dev.off()



#Selected CI plots
#=================
png('./Reports/Figures/SelectedCIConvergence_NoTitle.png', width=18, height=25, units='cm', res=300)
print(
    # ggplot2 plot with confidence intervals    
    ci_Plot <- ggplot(convergeSelected_df, aes(x=input, y=original, color = index )) +
        geom_point(aes(shape = index)) +
        geom_errorbar(aes(ymin = min..c.i., ymax = max..c.i.)) +
        #ggtitle("Confidence Interval reduction with increasing sample size")+
        # scale_color_discrete(name = "Index")+
        scale_shape_manual(name = "Index",values=c(16, 17, 5, 6))+
        scale_color_manual(name = "Index",values=c('#CC9966','lightgreen', '#993300', 'darkgreen'))+
        scale_size_manual(name = "Index",values=c(2,5,2,5))+
        #labs(#title = "Confidence Interval reduction with increasing sample size",
             #subtitle = "Location: Gunnedah  Sowing #2")+
        xlab("Input")+
        ylab("Sobol index value")+
        theme_bw() +
        theme(axis.text.x = element_text(angle = 90)) +
        facet_grid(target ~ sampleSize )
)

dev.off()

