#Plots of Sobol indices (six inputs) generated by ML emulators
#============================================================================
# Random Forest and ANN emulators for 6 output targets by 6 Inputs
#   across 3 sowings by 3 locations [1 sampling level = 100000 samples]


rm(list = ls())

library(ggplot2)
library(dplyr)

options(scipen=999)
#format(summary(caps), big.mark = ",") # using big.mark to add commas

# define the datapaths / files / settings
# project load directory = working directory ["U:/Paper #3/Data and Code/R"]
dataPath <- "./Reports/"

ANN_3ScenarioTestFile <- "ANN_3ScenarioTest.csv"
RF_3ScenarioTestFile <- "RF_3ScenarioTest.csv"


# Output strings
outputPath <- "./Reports/Figures/"
Emerald_graph1Name <- "Plot_Sobol_3Scenarios_Emerald"
Gunnedah_graph1Name <- "Plot_Sobol_3Scenarios_Gunnedah"
Horsham_graph1Name <- "Plot_Sobol_3Scenarios_Horsham"
#Horsham_graph2Name <- "aaPlot_B&W_3Scenarios_Horsham"

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

#Example #1
#==========
# my_ggplot <- ggplot(df_CI,        # Create default ggplot2 scatterplot
#                     aes(x = x_values,
#                         y = y_values)) +
#     geom_point() +
#     geom_errorbar(aes(ymin = lower_CI,
#                      ymax = upper_CI))
#
# my_ggplot  # Draw plot in RStudio
#

#Example #2
#==========
#ggplot(data, aes(x, y)) +        # ggplot2 plot with confidence intervals
#    geom_point() +
#    geom_errorbar(aes(ymin = lower, ymax = upper))

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

#Load  .csv data file of SOBOL Convergence data

#ANN models
sourceFile <- paste0(dataPath,ANN_3ScenarioTestFile)
ann_scenarios_df <- read.csv(sourceFile)

#RF models
sourceFile <- paste0(dataPath,RF_3ScenarioTestFile)
rf_scenarios_df <- read.csv(sourceFile)


# Combine the two ML models' dataframes into a single data source
allScenarios_df <- rbind(ann_scenarios_df,
                         rf_scenarios_df
                         )

# convert index names to report format
allScenarios_df$index[allScenarios_df$model == "RF" & allScenarios_df$index == "FirstOrder"]      <- "FirstOrder_RF"
allScenarios_df$index[allScenarios_df$model == "RF" & allScenarios_df$index == "TotalEffects"]   <- "TotalEffects_RF"
allScenarios_df$index[allScenarios_df$model == "ANN" & allScenarios_df$index == "FirstOrder"]      <- "FirstOrder_ANN"
allScenarios_df$index[allScenarios_df$model == "ANN" & allScenarios_df$index == "TotalEffects"]   <- "TotalEffects_ANN"


# convert target names to report format
allScenarios_df$target[allScenarios_df$target == "EmergenceDAS"] <- "(i) EmergenceDAS"
allScenarios_df$target[allScenarios_df$target == "FloweringDAS"] <- "(ii) FloweringDAS"
allScenarios_df$target[allScenarios_df$target == "PoddingDAS"]   <- "(iii) PoddingDAS"
allScenarios_df$target[allScenarios_df$target == "MaturityDAS"]  <- "(iv) MaturityDAS"
allScenarios_df$target[allScenarios_df$target == "Biomass"]      <- "(v) Biomass"
allScenarios_df$target[allScenarios_df$target == "GrainWt"]      <- "(vi) GrainWt"


# convert sowing codes to report format
allScenarios_df$sowing[allScenarios_df$sowing == "S1"] <- "Sowing 1"
allScenarios_df$sowing[allScenarios_df$sowing == "S2"] <- "Sowing 2"
allScenarios_df$sowing[allScenarios_df$sowing == "S3"] <- "Sowing 3"


Loc1Scenarios_df <- subset(allScenarios_df, location == "Emerald")
Loc2Scenarios_df <- subset(allScenarios_df, location == "Gunnedah")
Loc3Scenarios_df <- subset(allScenarios_df, location == "Horsham")

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#Generate graphs
#===============

#Emerald
outputFile <- paste0(outputPath,Emerald_graph1Name,".png")
png(outputFile, width=18, height=25, units='cm', res=300)
print(
    # ggplot2 plot with confidence intervals    
    ci_Plot_Emerald <- ggplot(Loc1Scenarios_df, aes(x=input, y=original, color = index )) + 
            geom_point(aes(shape = index)) +
            # scale_color_discrete(name = "Index")+
            scale_shape_manual(name = "Index",values=c(16, 17, 5, 6))+
            scale_color_manual(name = "Index",values=c('#CC9966','lightgreen', '#993300', 'darkgreen'))+
            scale_size_manual(name = "Index",values=c(2,5,2,5))+
            labs(title = "Sobol Analysis of phenology inputs for 6 target outputs over 3 sowing dates",
                 subtitle = "Location: Emerald    Sample Size: 100000")+
            xlab("Input")+
            ylab("Sobol index value")+
            theme_bw() +
            #theme(plot.title=element_text(hjust=0.5))+
            theme(axis.text.x = element_text(angle = 90)) +
        facet_grid(target ~ sowing),
)

dev.off()

#Gunnedah
outputFile <- paste0(outputPath,Gunnedah_graph1Name,".png")
png(outputFile, width=18, height=25, units='cm', res=300)
print(
    # ggplot2 plot with confidence intervals    
    ci_Plot_Gunnedah <- ggplot(Loc2Scenarios_df, aes(x=input, y=original, color = index )) + 
        geom_point(aes(shape = index)) +
        # scale_color_discrete(name = "Index")+
        scale_shape_manual(name = "Index",values=c(16, 17, 5, 6))+
        scale_color_manual(name = "Index",values=c('#CC9966','lightgreen', '#993300', 'darkgreen'))+
        scale_size_manual(name = "Index",values=c(2,5,2,5))+
        labs(title = "Sobol Analysis of phenology inputs for 6 target outputs over 3 sowing dates",
             subtitle = "Location: Gunnedah    Sample Size: 100000")+
        xlab("Input")+
        ylab("Sobol index value")+
        theme_bw() +
        #theme(plot.title=element_text(hjust=0.5))+
        theme(axis.text.x = element_text(angle = 90)) +
        facet_grid(target ~ sowing),
)

dev.off()

#Horsham
outputFile <- paste0(outputPath,Horsham_graph1Name,".png")
png(outputFile, width=18, height=25, units='cm', res=300)
print(
    # ggplot2 plot with confidence intervals    
    ci_Plot_Horsham <- ggplot(Loc3Scenarios_df, aes(x=input, y=original, color = index )) +
        geom_point(aes(shape = index)) +
        # scale_color_discrete(name = "Index")+
        scale_shape_manual(name = "Index",values=c(16, 17, 5, 6))+
        scale_color_manual(name = "Index",values=c('#CC9966','lightgreen', '#993300', 'darkgreen'))+
        scale_size_manual(name = "Index",values=c(2,5,2,5))+
        labs(title = "Sobol Analysis of phenology inputs for 6 target outputs over 3 sowing dates",
             subtitle = "Location: Horsham    Sample Size: 100000")+
        xlab("Input")+
        ylab("Sobol index value")+
        theme_bw() +
        #theme(plot.title=element_text(hjust=0.5))+
        theme(axis.text.x = element_text(angle = 90)) +
        facet_grid(target ~ sowing)
)

dev.off()





