#Plots of Correlation Matrices of Sobol indices (six inputs) generated by ML emulators
# for each of the six output targets
#====================================================================================
# Random Forest and ANN emulators for 6 output targets by 6 Inputs
#   across 3 sowings by 3 locations [1 sampling level = 100000 samples]


rm(list = ls())

library(ggplot2)
library(ggcorrplot)
library(dplyr)

options(scipen=999)
#format(summary(caps), big.mark = ",") # using big.mark to add commas

# define the datapaths / files / settings
# project load directory = working directory ["U:/Paper #3/Data and Code/R"]
dataPath <- "./Reports/"

ANN_3ScenarioTestFile <- "ANN_3ScenarioTest.csv"
RF_3ScenarioTestFile <- "RF_3ScenarioTest.csv"


# Output strings
outputPath <- "./Reports/Figures/"


#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#Load  .csv data file of SOBOL Convergence data

#ANN models
sourceFile <- paste0(dataPath,ANN_3ScenarioTestFile)
ann_scenarios_df <- read.csv(sourceFile)

#RF models
sourceFile <- paste0(dataPath,RF_3ScenarioTestFile)
rf_scenarios_df <- read.csv(sourceFile)


# Combine the two ML models' dataframes into a single data source
allScenarios_df <- rbind(ann_scenarios_df,
                         rf_scenarios_df
)

# convert index names to report format
allScenarios_df$index[allScenarios_df$model == "RF" & allScenarios_df$index == "FirstOrder"]      <- "FirstOrder_RF"
allScenarios_df$index[allScenarios_df$model == "RF" & allScenarios_df$index == "TotalEffects"]   <- "TotalEffects_RF"
allScenarios_df$index[allScenarios_df$model == "ANN" & allScenarios_df$index == "FirstOrder"]      <- "FirstOrder_ANN"
allScenarios_df$index[allScenarios_df$model == "ANN" & allScenarios_df$index == "TotalEffects"]   <- "TotalEffects_ANN"


# convert target names to report format
allScenarios_df$target[allScenarios_df$target == "EmergenceDAS"] <- "(i) EmergenceDAS"
allScenarios_df$target[allScenarios_df$target == "FloweringDAS"] <- "(ii) FloweringDAS"
allScenarios_df$target[allScenarios_df$target == "PoddingDAS"]   <- "(iii) PoddingDAS"
allScenarios_df$target[allScenarios_df$target == "MaturityDAS"]  <- "(iv) MaturityDAS"
allScenarios_df$target[allScenarios_df$target == "Biomass"]      <- "(v) Biomass"
allScenarios_df$target[allScenarios_df$target == "GrainWt"]      <- "(vi) GrainWt"


# convert sowing codes to report format
allScenarios_df$sowing[allScenarios_df$sowing == "S1"] <- "Sowing 1"
allScenarios_df$sowing[allScenarios_df$sowing == "S2"] <- "Sowing 2"
allScenarios_df$sowing[allScenarios_df$sowing == "S3"] <- "Sowing 3"

#combine scenario labels with input names to create unique identifiers
# str_sub(x, start= -6)

allScenarios_df$scenarioID <- paste0(substr(allScenarios_df$location,1,1),
                                 substr(allScenarios_df$sowing,nchar(allScenarios_df$sowing),nchar(allScenarios_df$sowing)))

allScenarios_df$corrID <- paste0(substr(allScenarios_df$location,1,1),
                                 substr(allScenarios_df$sowing,nchar(allScenarios_df$sowing),nchar(allScenarios_df$sowing)),
                                 "_",
                                 allScenarios_df$input)

# create list of unique input strings
inputs_lst <- unique(c(as.character(allScenarios_df$input)))

# select subset for each ML model
RF_S1_all_df <- subset(allScenarios_df, (model == "RF" & index == "FirstOrder_RF"))
#RF_S1_df <- data.frame(cbind(RF_S1_all_df$corrID,RF_S1_all_df$scenarioID, RF_S1_all_df$original))
RF_EmergenceDAS_S1_df <- subset(RF_S1_all_df,target == "(i) EmergenceDAS")

    # # created vector with 5 characters
    # columns= c("id","names","address","phone","aadhar no")
    # 
    # # pass this vector length to ncol parameter
    # # and nrow with 0
    # myData = data.frame(matrix(nrow = 0, ncol = length(columns)))
    # 
    # # assign column names
    # colnames(myData) = columns
    # 
    # # display
    # print(myData)


#mat_1 <-as.dist(round(cor(RF_S1_df[,2]),2))




#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#Generate graphs
#===============
